/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_indoor_walking_Sample3View */

#ifndef _Included_com_example_indoor_walking_Sample3View
#define _Included_com_example_indoor_walking_Sample3View
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_indoor_walking_Sample3View
 * Method:    FindFeatures
 * Signature: (II[B[I)V
 */
JNIEXPORT void JNICALL Java_com_example_indoor_walking_Sample3View_FindFeatures
  (JNIEnv *, jobject, jint, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
